env:
  browser: true
  es2021: true
  node: true
extends:
  - airbnb
  - plugin:solid/typescript
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
  - react
  - solid
  - only-warn
rules:
  react/react-in-jsx-scope: off
  react/jsx-filename-extension: off
  react/no-unknown-property: off
  import/extensions: off
  import/no-unresolved: off
  import/no-extraneous-dependencies: off
  eqeqeq: off
  react/jsx-no-undef: off
  no-undef: off
  react/destructuring-assignment: off
  react/require-default-props: off
